blueprint:
  name: Automatic air conditioner for winter and summer, monitoring presence, time slot.
  description:  "`- Version: 1.0 -`\n\n This blueprint is for using the air conditioner automatically in both winter and summer, based on a start and end temperature. 

          Optionally, you can enable:

          - Home presence control 
          
          - Notifications
          
          - Decide on the time slot for operation"


  domain: automation
  input:

    language:
      name: Select language
      description: 'Select the language for the text of notifications.'
      default: English
      selector:
        select:
          mode: dropdown
          options:
            - English

    season:
      name: Select season
      description: 'Select the season of use.'
      default: Summer
      selector:
        select:
          mode: dropdown
          options:
            - Summer
            - Winter
  
    hvac_modes:
      name: Hvac modes
      description: 'Select the mode to be set to the air conditioner.'
      default: cool
      selector:
        select:
          mode: dropdown
          options:
            - heat
            - cool

    climate:
      name: Thermostat Entity
      description: 'Select thermostat to configure.'
      selector:
        entity:
          domain: climate

    primary_temperature_sensor:
      name: Primary Temperature Sensor
      description: 'Select temperature sensor as the primary sensor to be used by the thermostat.'
      selector:
        entity:
          domain: climate, sensor

    set_temperature_climate:
      name: Set temperature climate
      default: 78
      description: 'Select the temperature to be set at climate.'
      selector:
        number:
          min: 60
          max: 85
          unit_of_measurement: 째F
          mode: slider
          step: 1

    presence_home:
      name: Presence Home
      description: 'Select the group consisting of person.'
      default: group.presence_home_disabled
      selector:
        entity:
          domain: group
          multiple: true

    target_temperature_start:
      name: Target temperature start
      default: 78
      description: 'Set the target temperature to startup the Thermostat.'
      selector:
        number:
          min: 60
          max: 85
          unit_of_measurement: 째F
          mode: slider
          step: 1

    target_temperature_stop:
      name: Target temperature stop
      default: 77
      description: 'Set the target temperature to shutdown the Thermostat.'
      selector:
        number:
          min: 60
          max: 85
          unit_of_measurement: 째F
          mode: slider
          step: 1

    delay_temperature_stop:
      default: 10
      name: Delay temperature stop
      description: 'Set the climate shutdown delay since the target temperature has been reached.'
      selector:
        number:
          min: 0
          max: 30
          unit_of_measurement: min
          mode: slider
          step: 1

    outside_temperature_stop:
      name: Outside temperature stop
      default: 74
      description: 'Set the outside air temperature to shutdown the Thermostat.'
      selector:
        number:
          min: 60
          max: 90
          unit_of_measurement: 째F
          mode: slider
          step: 1

    start_time:
      name: Start time
      default: "00:00:00"
      description: 'Set automatic operation start time.'
      selector:
        time: 

    stop_time:
      name: Stop time
      default: "00:00:00"
      description: 'Set automatic operation end time.'
      selector:
        time: 

    notify_device:
      name: Device to notify push
      default: false
      description: 'Device needs to run the official Home Assistant app to receive notifications.'
      selector:
        device: 
          integration: mobile_app

mode: parallel
variables:
  season: !input season
  target_temperature_start: !input target_temperature_start
  climate: !input climate
  target_temperature_stop: !input target_temperature_stop
  presence_home: !input presence_home
  outside_temperature_stop: !input outside_temperature_stop
trigger:
- platform: numeric_state
  entity_id: !input climate
  attribute: current_temperature
  above: !input target_temperature_start
  id: climate_on
- platform: numeric_state 
  entity_id: !input climate
  attribute: current_temperature 
  below: !input target_temperature_start
  id: climate_on
- platform: numeric_state
  entity_id: !input climate
  attribute: current_temperature 
  below: !input target_temperature_stop
  for: 
    minutes: !input delay_temperature_stop
  id: climate_off
- platform: numeric_state
  entity_id: !input climate
  attribute: current_temperature 
  above: !input target_temperature_stop
  for: 
    minutes: !input delay_temperature_stop
  id: climate_off
- platform: time
  at: !input stop_time
  id: climate_off
- platform: time
  at: !input start_time
  id: climate_on
- platform: state
  entity_id: !input presence_home
  from: 
      - not_home
      - home
  to: 
      - not_home
      - home
  id: presence_home
action:
- alias: Spegni climate
  if: 
    - "{{not is_state(climate,'off')}}"
    - or: 
      - "{{ trigger.id == 'presence_home' and trigger.to_state.state == 'not_home'}}"
      - "{{ trigger.id == 'climate_off' and season == 'Winter' and (state_attr(climate,'current_temperature')|float(0) > target_temperature_stop|float(0) )}}"
      - "{{ trigger.id == 'climate_off' and season == 'Summer' and (state_attr(climate,'current_temperature')|float(0) < target_temperature_stop|float(0) )}}"
      - "{{ trigger.id == 'climate_off' and trigger.platform == 'time'}}"
  then:
      - service: climate.turn_off
        target:
          entity_id: !input climate
      - domain: mobile_app
        type: notify
        device_id: !input notify_device
        title: "AIR CONDITIONER."
        message: "{% if (trigger.id == 'climate_off' or trigger.id == 'presence_home')%} Automatic air conditioner shutdown.
                  {% elif trigger.id == 'moisture_climate_off' %} Air conditioner off for water drain container full.
                  {% endif %}"